# fly.toml app configuration file generated for
# kotaemon-hidden-star-2359 on 2025-04-23T17:05:11-05:00
#
# See https://fly.io/docs/reference/configuration/
# for information about how to use this file.
#

app = 'kotaemon-cornerstone'
primary_region = 'ord'

[build]
  dockerfile = 'Dockerfile'

[[mounts]]
  source = 'ktem_volume'
  destination = '/app/ktem_app_data'

[http_service]
  internal_port = 7860
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '8gb'
  cpu_kind = 'shared'
  cpus = 4
